### ISSUE TITLE
Freezes Linux Mint cinnamon while updating during internet outage

### ISSUE THREAD

**Issue by BMarkley** [thegli/yfquotes-cinnamon-desklet#3]
If the app tries to update the data during an internet outage my entire cinnamon Linux mint desktop freezes for several minutes. It seems to hog all the computer resources or something - this can also cause other programs to crash, loss of productive work, etc. I love the application but this bug makes it unusable.

**Comment by thegli** [comment]
@BMarkley I tried to reproduce the issue by manually disabling the wifi, then changing the desklet's configuration (e.g. hiding a field). The expected error message was then displayed in the desklet.
I could not reproduce the problem you reported. The cpu load did show any spikes or even heavy load, and Cinnamon responded normally.

**Comment by BMarkley** [comment]
odd. I don't know why I'm having this happen and you are not. It's definitely the extension causing it, cause if it's disabled this does not happen. I can even trigger it by having no internet and changing a parameter in the settings forcing it to reset the data - which causes the desktop to hang for about a minute. 

One thing that may or may not matter is that I don't have Wifi. I'm connected directly to the router with ethernet.

I'm still running the desklet so if there is anything you want me to try on my end, just say the word. 

Thanks
-Brian

**Comment by BMarkley** [comment]
I updated the kernel to 5.13.0-30 and the problem fixed itself.

**Comment by thegli** [comment]
Glad to hear that the problem went away.
