### ISSUE TITLE
Stopped working for me both in Linux Mint 21.2 and LMDE 5

### ISSUE THREAD

**Issue by C8forT** [thegli/yfquotes-cinnamon-desklet#4]
The desklet displays the message "Error: Yahoo Finance service not available!" both in Linux Mint 21.2 and LMDE 5.

This happened a while back, but an update came through that fixed it.  The problem has re-appeared, though.

**Comment by benchrest** [comment]
Failed same time on Linux Mint 20.3 Cinnamon

**Comment by thegli** [comment]
The latest update brought a new setting "Send custom User-Agent header". Enable it in the configuration (first tab, last one at the bottom).

**Comment by thegli** [comment]
@C8forT A new release is out that might fix your issue.
If you downloaded the desklet from my repo, and did a manual install, then please try the latest [version 0.9.0](https://github.com/thegli/yfquotes-cinnamon-desklet/releases/tag/v0.9.0).
If you installed from the official Cinnamon repo, then you have to wait until [PR 912](https://github.com/linuxmint/cinnamon-spices-desklets/pull/912) gets merged.

Either way, let me know if the latest changes help.

**Comment by thegli** [comment]
Got no feedback, assume that the latest version worked.
