### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by MajorMitchel** [thegli/yfquotes-cinnamon-desklet#5]
Hi Thomas, 

still receive an error message when starting the desklet (partially in German):

Fehler: Empfang von Autorisierungs-Crumb ist fehlgeschlagen! Finanzdaten-Abfrage nicht möglich.
Status: 429 Too many Requests

Seems, that the update from August did not work for me. Do you have any idea how to solve the problem?

Thank you and kind regards
Tobias

**Comment by thegli** [comment]
Hi Tobias

Just checking, but is the configuration option for sending a custom User-Agent header enabled? By default, this option is disabled.

![image](https://github.com/thegli/yfquotes-cinnamon-desklet/assets/38955561/590e323a-a06f-4fb7-9294-9f5443ed7097)

Let me now if this helps.

Kind regards,
Thomas

**Comment by MajorMitchel** [comment]
Hi Thomas, 

custom User-Agent header option was disabled. Problem is solved after enabling this option!
Thank you very much for your quick support and the easy solution !!

Kind regards
Tobias

**Comment by thegli** [comment]
Glad to hear that you could solve the problem, and thanks for letting me know.
I will close this issue.
