### ISSUE TITLE
Faulty Symbol Is Blocking Display in Desklet

### ISSUE THREAD

**Issue by paintdog** [thegli/yfquotes-cinnamon-desklet#7]
An incorrect symbol in the list of quote symbols is probably causing the data to be retrieved incorrectly. I now get the "Error: Yahoo Finance service not available! Status: 0 null" message and no financial data are displayed. I removed a symbol and the display works again.

Can anyone verify that this is the cause of the error? Maybe you can test it with "GOUG.DE" (no real symbol).

The actual behaviour makes it difficult for me to find the error. Is it possible that a line with a note about the error appears when there is an incorrect symbol? It can happen from time to time that a symbol changes or is removed (e.g. delisting).

BTW: Great work.

**Comment by thegli** [comment]
I cannot reproduce the problem. Unknown symbols do either show up as "N/A" in the view, or are ignored entirely.

This is how it looks like on my machine with the existing symbol AMZN and your non-existing example GOUG.DE.
![image](https://github.com/thegli/yfquotes-cinnamon-desklet/assets/38955561/88c0ede3-f768-4eea-b821-2b00db53810a)

**Comment by paintdog** [comment]
You're right. I can't reproduce the problem, today. Sorry for disturbing. Thank you for your efforts and this desklet!

**Comment by thegli** [comment]
No harm done :relieved: I'm happy that you like the desklet.
And thanks to your input, I discovered a minor shortcoming in case the quotes list is empty.
