### ISSUE TITLE
Desklet Disappeared with latest update (22/08/24 - Linux Mint 21.3 Cinnamon)

### ISSUE THREAD

**Issue by David-DeZ** [thegli/yfquotes-cinnamon-desklet#8]
The Desklet was just updated (22/08/24 - Linux Mint 21.3 Cinnamon) and has disappeared from the desktop - yet via the control panel I can access the configuration and all appears fine.

**Comment by David-DeZ** [comment]
Just received another update - same problem

**Comment by thegli** [comment]
Did you see anything suspicious in the log?
The Cinnamon log can be accessed with the shortcut "Alt-2", and the command "lg". In the opened application "Melange", select the "Log" tab and look for any warnings/errors, specifically entries with "yfquotes@thegli".
On the "Extension" tab, you see all loaded Spices. Is the desklet in the list?

And since you can still access the settings - did you try to load the default values (menu entry "Reset to defaults")?

**Comment by David-DeZ** [comment]
Thanks Thomas for helping!
1. Alt-2 does nothing either on my desktop or in the Terminal
2. Doing a reset to default kind of works - but it only resets the visible Quote tabs, the extra hidden one (accessible via the top left arrow) also requires a reset - anyway it works mostly, although a few times it caused LM to crash (screen went black - requiring a re-logon). Once I paste in my stocks, it disappears - yet there has been no changes and it worked before that update.
Sorry

**Comment by David-DeZ** [comment]
Seems to be OK now - I had to add my stocks in 5 at a time (I watch about 60). If I added all it fully disappeared. I also had to adjust the layout height as I added - it was at 1080 - but had to be shortened and then lengthened as each group was added eventually back up to 1080,  Weird!

**Comment by thegli** [comment]
Glad that it (somehow) works again :sweat:
And I gave you a wrong shortcut :facepalm: The correct one is "Alt-**F2**"

It's odd that entering the full list at once did not work. If I understand you correctly, then you entered about 60 symbols, then clicked the (newly added in this version) "Refresh" button to reload them all, and then Cinnamon crashed? :worried: 
I also tested with 60 quotes, but could not reproduce this (highly undesired) behavior.

Here's an alternative you may want to try (in case the instabilities return): distribute your quotes across **multiple desklet instances**. Then there are less data to be fetched for each list which should reduce the chance for lags.

Regarding the layout: Yes, the desklet does not automatically adopt its size to the content. If the "vertical scrollbar" option is disabled (the default), then the entries simply overflow at the bottom, and you:

- either increase the height manually
- or you enable the vertical scrollbar

Hope these information are of some value.

**Comment by David-DeZ** [comment]
Thanks once again Thomas!
Yes - adding in all my 60 caused the desklet to disappear and in two occasions, LM to crash. Still strange why it first disappeared when the desklet was first updated. 
But - it's working now!  You're right, my sizing problem was probably due to the scrollbar not being turned on. I like yous suggestion to do multiple desklets if it happens again. How do you do that?
Although probably not connected to my problem - I noted  that the two Quote Tabs do not reset to defaults simultaneously and can list different stocks - you may wish to address this.

Your desklet and friendly support is much appreciated!!!
David

**Comment by thegli** [comment]
To get multiple instances, open the "Desklets" application, select the desklet in the list, and press the "+" (Add) button. A second instance (with default values) will appear.
You can have up to 10 instances at the same time, and each instance manages its own settings (which you most likely want to export to *separate* files :smile:)

And what exactly do you mean with *the two Quote Tabs do not reset to defaults simultaneously and can list different stocks*? I'm not getting that one :face_with_diagonal_mouth:

**Comment by David-DeZ** [comment]
Thanks! Neat that you can have multiple desklets! 

Sorry, I didn't explain the situation fully. Hopefully I'll do better with this attempt. 
When you open configuration, the left tab is QUOTES. If you hit one of the top left arrows (beside Quotes) it will toggle the Quotes between having 2 to having 5 options under "Data Updates".
While in Quotes, if you "Reset to defaults" it will replace the stocks listed  to the default list - however if you toggle to the other Quotes, the original list of stocks will be there, not the default ones.

I hope that I've been clearer. As you can see, it probably has nothing to do with my issue, but while playing trying to solve my problem by resetting to defaults, I came across it. Perhaps it caused the LM to crash? In any case, it is an anomaly!

Hope that I've been of help!

BESTEST
David

**Comment by thegli** [comment]
Ok, I'm probably too stupid/too tired for this :laughing:
This is how the settings dialogue looks on my machine (also LM 21.3) using the default values:

![image](https://github.com/user-attachments/assets/7decd047-6526-4493-bc6d-de79173aea2c)

Anyhow, glad to be of help, and thanks for your input!
Thomas

**Comment by David-DeZ** [comment]
Mine is different!

Note the two arrows that do the toggle!

![image](https://github.com/user-attachments/assets/c96576f3-baaa-4c6e-8769-3ff5d8200e0b)

**Comment by David-DeZ** [comment]
Mine is different - note the arrows at the left top that do the toggle
![image](https://github.com/user-attachments/assets/95e5e1e8-d887-4c80-9730-bf3b681e5035)

**Comment by David-DeZ** [comment]
After hitting an arrow
![image](https://github.com/user-attachments/assets/5c6dddd8-a1b7-40ac-92ad-e86eaaaf29ef)

**Comment by David-DeZ** [comment]
I'm tired too (GMT+3) - Be Well - Tomorrow is another day!

**Comment by David-DeZ** [comment]
Having slept on it - here are some points to take into consideration.

1. We have differing versions - strange (a mystery unto itself) - the problem started with the update of 22/8 and continued even with an additional update on 23/8 - my software sources are the default (ie not mirrors):  packages.linuxmintcom & archive.ubuntu.com/ubuntu
2. I do not remember the arrows immediately prior to the problem arising - perhaps it was temporarily in use as a result of the issue when we last interchanged   []https://github.com/linuxmint/cinnamon-spices-desklets/issues/840(url)
3. Another possible clue - when I added in my watchlist 5 items at a time I noticed that my currency items (eg CADUSD=X) had been in lower case - this had not been a problem before, but I still made them into upper case - coincidentally, after that change along with adding 5 at a time, it started to work.

**Comment by David-DeZ** [comment]
Sorry Thomas - playing a bit more and came upon:

There are errors now in Looking Glass!
error t=2024-08-24T09:10:41Z yfquotes@thegli - TypeError: symbolCustomization is undefined

Also I noted that my watchlist (copied from the config before I reset to defaults) is not exactly the one I used just before the problem arised! It looks more like my watchlist from about a year ago!

I have not done any type of restore and have yet to put in LM 22!

We are entering the twilight zone!!!!!

**Comment by thegli** [comment]
Thanks for the further analysis. Very strange indeed :ghost: 
Let's try to sort them all out:

1. *TypeError: symbolCustomization is undefined*: These errors I also found on my installation in the meantime. I already identified the cause (when Yahoo does return a different symbol than the one that was sent - this seems to happen only rarely),  and I will provide a fix for this.
2. *Instabilities*: I found a rather nasty problem that is not new, and can cause network congestion and maybe general desktop instability (not to say "crash"). This problem occurs whenever settings are imported from a file, causing multiple data updates to be fired in parallel (instead of only one). I will have to think about it how to tackle it, because it affects the mechanism how setting changes are picked up.
3. *Arrow navigation in settings*: This I never saw before. It looks like two different sets of settings are present at the same time.
Have you already tried to uninstall the desklet (after you made a copy of the quotes list), and then download it again, add it to the desktop again, and then only copy the quotes into the textbox (but no "import from a file"), and apply them by clicking the "refresh" button?
4. *lower/uppercase currency rates*: AFAIK, Yahoo Finance always returns symbols in uppercase, but it accepts lowercase spelling as well. It shouldn't make a difference if we write "cadusd=x" or "CADUSD=X" or even "cAdUSd=x". Personally, I spell - out of habit - the symbols always in uppercase.

That should be all, I hope :sweat_smile:

**Comment by David-DeZ** [comment]
That did it, Thomas - THANKS!

I did what you suggested - copying my watchlist, noting my other preferences, then fully deleting the Desklet and re-downloading it, re-installing it and configuring it. No more arrows! Looks great- exactly as it did before this adventure started.

It looks like the other two problems (1&2 in your list), are serious and #2 complicated whatever my problem was and my attempts to recover from it.

Hopefully that's it - although it was enjoyable and an honour to work with you, I hope not to have to bother you again. Nonetheless, I will keep this issue open until I get another update of your desklet via LM, which triggered this episode of the Twilight Zone, in case it reoccurs.

Be well Thomas, and thanks again!

BESTEST
David

**Comment by thegli** [comment]
[This PR](https://github.com/linuxmint/cinnamon-spices-desklets/pull/1264) addresses 1 and 2.

While I could fix the excessive request creation, there was a price to pay: Importing settings from a file no longer auto-reloads the quotes, and requires now a click of the "Refresh" button (which moved to the bottom of the screen). Depending on the previous dimensions, content may therefore overflow temporarily.

It's not the nicest solution, but the former situation was (technically speaking) much worse, and put some unnecessary stress onto Cinnamon.

Let me know what you think of it :owl:

**Comment by David-DeZ** [comment]
Hi Thomas

Installed the update, checked the config, saw the refresh button had moved and everything looks fine. So, as requested I opened a second desklet with the intent to import my saved configuration, do the refresh and  give you my opinion. 
1. First thing I noticed checking the second config is that the arrows re-appeared! Both "Quotes" Tabs had the refresh moved and all 4 options (ie had User-Agent Header) - but one had the default stocks and one had my existing list. Checking the config now of my existing one, it too had the arrows.
2. On the second one's config, in the default quotes, I did the import of my saved config and refresh. All worked great.
3. After deleting the second one, I then checked the config of my existing one and the arrows had disappeared.

So - in general my opinion is (as usual with your work) positive! And we now have a clue why I previously had the arrows, however they were there before I added the second one (or even knew it was possible), it listed stocks from a year ago and I only had one desklet visible. My guess is that I perhaps unknowingly created a second instance a year ago, prior to when you did the fix for the User-Agent Header, thus giving me one Quote Tab with and one without, and somehow the remnant persevered and eventually perhaps caused me the disappearing issue of last week when the update broke the camels back, so to say.. 

Pending your reply  I'll leave this issue open - but as far as I'm concerned I can close it and will do so unless you want further follow up.

Again - many thanks - your sharing of your talents and skills by providing this desklet, along with your time, efforts, and friendly assistance are all much appreciated!

BESTEST
David

**Comment by thegli** [comment]
Hi David

Thanks for the throughout "beta" testing! I'm really glad that it works now for you.

Now I see the arrows, too :laughing:  And you're absolutely correct: this is the way how Cinnamon presents the settings of multiple active desklet instances. Really strange that I never noticed that :frowning: 

Regarding the import/export of desklet settings: When a settings file from an older desklet version is imported, then Cinnamon performs an in-flight merging with the current default settings. As long as these merged settings are not exported, this in-flight merge will happen once more next time the same old settings are loaded again.
So exporting the settings is never a bad idea :bulb: 

And a big Thank-You for your kind and encouraging words! :star_struck: 

I'm still not super-happy with the manual refresh workaround I had to impose on the users. So far I couldn't figure out a way to bring back the old behavior. Well, let' see...

If you don't mind, you can close the issue for now. If needed you can reopen it anytime.

Cheers,
Thomas

**Comment by David-DeZ** [comment]
Thanks again Thomas.

I'll close this issue even though the original problem has not been explained, although resolved. However, debugging brought up other items that you have now addressed, which may have been the underlying cause of my manifestation!

I don't share your concern about having to manually do a refresh when importing settings. IMHO, no big deal!

Also not explained how I had settings for two desktop instances when only having one live - how they dated from about a year ago - and that I have no recollection of having previously exported or imported settings!  But that's why we love IT - it's full of mysteries!

It's been a pleasure!

BESTEST
David
