### ISSUE TITLE
Would be nice to allow empty lines to separate stocks

### ISSUE THREAD

**Issue by eGit** [thegli/yfquotes-cinnamon-desklet#9]
Great desklet. For increased readability, empty lines that separate different types of quotes would be really helpful. The // symbols could be used to empty lines. All text after the // symbols is ignored and an empty line is introduced in the desklet.

Example:
GC=F
SI=F
PSLV

// empty line

BTC-USD

// empty line

^GDAXI
^DJI

**Comment by thegli** [comment]
At the moment I don't see an easy fix for this.
Have you tried to create separate desklet instances for the different types?

**Comment by eGit** [comment]
Oh. I guess multiple instance of the Desklet would be possible.

I thought it would be an easy fix to introduce this feature, by just adding an empty UI Block.
